name: 'Share Jobs Data'
description: 'Share data between GitHub Actions jobs'

inputs:
  share-id:
    required: true
  mode:
    required: true
  key:
    required: true
  value:
    required: false

outputs:
  data:
    description: 'shared data'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: database
  color: yellow
